= 💪 BODY

== Health is the ultimate wealth
If you are healthy of mind and body you can always do something to make your life better.

Without your health you have nothing, make it a top priority in life. 

Taking care of your body and mind daily is not a waste of time.

== Excercise your body daily
Make sure you move your body on a daily basis. Morning excercise will make you feel better about the rest of the day, it will give you momentum to achieve more. For instance, just running can also be a great way to process what's happening in your life and to get creative towards your immediate or long term goals.

Daily excercise can be part of a ritual for high productivity. Whenever I don't excercise I'm usually less productive.

== Do not eat more than you need
One meal a day is actually more than enough, two meals are easy.

Our bodies are the product of tens of thousands of years of evolution and they're not meant to have as many calories as today's food abundance is easily able to provide us, this, along with lack of mobility is the reason why almost everybody around us is obese.

Intermittent fasting has an array of health benefits in hormonal control,  blood sugar levels, improved cell reproduction/destruction, rejuvenation and life expectancy, clearer thinking, also, it helps you remain humble.

== Drink a lot of water
Have with you a 1 or 2 liter water container all day. To make it easier I add lemon juice and ice. Drinking water makes intermittent fasting much easier. You know you're doing it right if your urine is clear.

== Run or do cardio for at least 45mins to 1 hour a day
If you can however run 6 miles (10km) this is the sweet spot for cardio and endorphins.

== Cardio in the mornings, weights/strength/technical training in the evenings
Morning is an awesome time to get cardio in, especially cardio on an empty stomach. By doing some low moderate intensity cardio on an empty stomach, you are burning primarily fat. Cardio helps keep your metabolism in check, gives you a stronger heart (of course) and better breathing and endurance for whatever other physical activities.

Then for your second workout session of the day, you no longer need to worry about time or energy spent on cardio. After a judicious warm up to avoid injuries you will be solely focused on what you're about to train, in my case it's climbing, and then if I have time left I will do weights.
