= 💪 BODY

== Health is the ultimate wealth
If you are healthy of mind and body you can always do something to make your life better.

Without your health you have nothing, make it a top priority in life. 

Taking care of your body and mind daily is not a waste of time.

== Excercise your body daily
Make sure you move your body on a daily basis. Morning excercise will make you feel better about the rest of the day, it will give you momentum to achieve more. For instance, just running can also be a great way to process what's happening in your life and to get creative towards your immediate or long term goals.

Daily excercise can be part of a ritual for high productivity. Whenever I don't excercise I'm usually less productive.

== Do not eat more than you need
One meal a day is actually more than enough, two meals are easy.

Our bodies are the product of tens of thousands of years of evolution and they're not meant to have as many calories as today's food abundance is easily able to provide us, this, along with lack of mobility is the reason why almost everybody around us is obese.

Intermittent fasting has an array of health benefits in hormonal control,  blood sugar levels, improved cell reproduction/destruction, rejuvenation and life expectancy, clearer thinking, also, it helps you remain humble.

== Drink a lot of water
Have with you a 1 or 2 liter water container all day. To make it easier I add lemon juice and ice. Drinking water makes intermittent fasting much easier. You know you're doing it right if your urine is clear.

== Run or do cardio for at least 45mins to 1 hour a day
If you can however run 6 miles (10km) this is the sweet spot for cardio and endorphins.

== Cardio in the mornings, weights/strength/technical training in the evenings
Morning is an awesome time to get cardio in, especially cardio on an empty stomach. By doing some low moderate intensity cardio on an empty stomach, you are burning primarily fat. Cardio helps keep your metabolism in check, gives you a stronger heart (of course) and better breathing and endurance for whatever other physical activities.

Then for your second workout session of the day, you no longer need to worry about time or energy spent on cardio. After a judicious warm up to avoid injuries you will be solely focused on what you're about to train, in my case it's climbing, and then if I have time left I will do weights.

== Do strength training at least 4x/week
Lifting, Climbing, Martial Arts, Calistenics

== Resting is training
If you're going hard, leave a day or two of training, recovery is key to getting stronger. Listen to your body.

Sometimes it's also necessary to work out moderately and not "kill" yourself on every session so that you can train more regularly. This will depend on the phase of your training cycle.

== Be in nature as much as possible
Be around nature or at least outdoors exposed to the sun at least one hour a day. If the weather does not allow for this, consider moving to another city.

We are humans and there are multiple emotional, cognitive (focus, awareness) and health benefits to being outdoor and in nature.

== Stay away from Alcohol, Meth, Opiates, Cocaine, Heroin and Nicotine
Alcohol which is a widely accepted and encouraged drug by friends is very destructive and it has also very bad effects when it comes to ageing. It's total crap, stay away from it. If you must drink, do so very moderately, do not make it a habit.

Beer? no more than two. Wine? no more than two glasses. Whiskey or stronger spirits, add ice and sip it very slowly. Getting wasted is stupid, you're literally poisoning your body and all the bad reactions like puking, headaches are your body trying to rid of the alcohol.

I have lost multiple loved ones to alcohol alone.

The other drugs mentioned are self destructive and highly addictive, do not even try, you will regret them.

== Whey Protein and Glutathione

Whey is a protein complex derived from milk with a diverse range of health benefits. It is a rich source of the essential amino acids in higher concentrations compared with vegetable sources such as soy. 

It contains a high concentration of branched-chain amino acids, which are important for tissue growth and repair.

Whey protein is rich in the sulfur-containing amino acids, which enhance the body’s antioxidant protection through intracellular conversion to glutathione.

Glutathione is arguably the most important water-soluble antioxidant found in the body, participating in crucial detoxification reactions in the liver. Glutathione is known to be essential to immunity, body antioxidative capacity, and general well-being, and decreased levels of glutathione are associated with a long list of ailments such as neurodegenerative disease, cirrhosis, and the aging process itself.

== Creatine

== Glutamine

== Glucosamine and Chondroitin
Glucosamine and chondroitin are two naturally occurring compounds within your cartilage. One of many important purposes of cartilage is to protect and cushion the ends of your bones.

In my experience (not sure if it's placebo), pain in my wrists, elbows and knees after I turned 30 from extended workouts has gone away after taking 2 pills for a few days in a row. Many experts still do not agree on its effectiveness, so just give them a skeptical try and see if they help you.
