= 🧠 MIND

xref:time.asciidoc[⌛ TIME] - xref:body.asciidoc[💪 BODY] - xref:mind.asciidoc[🧠 MIND] - xref:money.asciidoc[💰 MONEY] - xref:work.asciidoc[💼 WORK/LEADERSHIP] - xref:people.asciidoc[🤝 PEOPLE]

'''

== Do what you love and do it a lot
However, make sure that what you love doing doesn't harm others. Differentiate what you love doing from unhealthy addictions.

We are what we do and doing what we love makes us happy.

== Always be learning
If possible try learning something new everyday. The yearly compound growth of this habit will make you a far better person every year.

Books, audiobooks, podcasts, projects and listening to smart people.

== Get out of your comfort zone
This is how we truly grow, making that uncomfortable feeling going away because that which was hard is now easier.

== Keep your house in order
Always keep your room, dwelling, house, office, car, workplace clean and ordered.

You will feel better, more productive, happy and less prone to sickness, depression, demotivation.

An orderly life means more xref:time.asciidoc#keep-your-things-in-order-%EF%B8%8F[time] available.

== xref:body.asciidoc#stay-away-from-alcohol-meth-opiates-cocaine-heroin-and-nicotine[Stay away from Alcohol, Meth, Opiates, Cocaine, Heroin and Nicotine]

== Travel ✈️
When you do, explore the geography, learn the history, the culture, the language, the food, get out of your comfort zone.

I promise you will grow and learn things you wouldn't otherwise in any school, also you will not forget these lessons.

When you come back home you will be more aware of that which you have just experienced and it will make your own city a place with more things to offer, you will be able to relate to more people, you will be less judgemental, you will join the dots with your increased vocabulary and taste, there will be more restaurant options to eat from, and you will be able to mix the different cultures/foods, life will be much better after more travel.

== Not everybody is like you
When someone acts in a very different way, perhaps even stupid or irrational, be empathetic and try to think what their journey has been or if they have mental health issues causing such behaviours.

Know that everyone has a different upbringing, that not everybody was raised with the love and support you were so lucky to receive, or that perhaps they received even more love and support than you have.

There are also different levels of empathy people can feel/act out, for instance, autism is a big spectrum and when somebody seems like an asshole, perhaps they are somewhere on the less empathetic spectrum of it. This is very common among engineer/system types of people and uncommon among people-people who are very in tune with other people's feelings and needs.

Ultimately, yes, there are toxic people that you must push away from your life before they hurt you further.

This also applies to intellectual quotients, what may seem obvious to you might be really hard to comprehend for the majority of people towards 2/3rds of the normal curve.

== Study History, Sociology, Psychology, Logic, Politics

Make sure you have read Harari, Kahneman, The Skeptic's Guide to the Universe. Try to understand as much as you can how individuals and large groups of people think and have reacted in the past.

Learn about the history of the world, europe and its wars, capitalism, socialism and communism and their consequences, their virtues and flaws, learn about religion and the stories people believe in.
