== 💰MONEY

=== Do not spend more than you make
If you need to spend more, make sure you really need to spend that much. 

Try spending only on the things you absolutely need.

If you want to pamper yourself make sure you can afford it without putting yourself in an unconfortable financial situation.

If you're only spending on essentials and you're spending more than you make, make more money.

You can make more money by acquiring more valuable skills, by trading goods/stocks/currencies/other people's services.

=== Track your income and spending
When you're getting started with money, try having a simple spreadsheet to track every dollar that comes in and out of your networth.

This will help you understand the value of your money and time and it will help you realize what you really need and what expenses can be removed from your monthly budget.

=== Avoid debt, however it can be a great tool under the right conditions
Avoid debt unless it's absolutely necessary or you have 10x the collateral to pay it back.

If you will borrow money you must make sure you're paying the right amount of interest for the risk you represent, which should be low if you have 10x the collateral to pay it back.

Debt is enslaving if you struggle to pay it back, and not paying on time means interest will accrue on top of interests making it very hard or impossible to pay. 

Debt however can be a great tool when interest rates are very low, you can see it as "cheap money" if you know with certainty you will grow the capital you've borrowed to make more than the interest you'll be paying on it.
In the US you can tax deduct the interest payments and lower your tax burden.
Debt is useful when the economy shows inflationary signs and you know the value of money is lost at a faster rate than the interest you're paying.

=== Do not invest unless you're willing to lose 100% of that capital

Do not invest vital savings. Do not invest money you or your family will need.

Do not get in debt you can't repay to invest.

You must be able to burn the money you're about to invest and be fine with that. This will remove emotions like fear and greed from your investment strategy and you will be able to follow through with it despite possible temporary crashes or bear cycles, as well as being able to get out of your investment position once your initial target has been met and not lose it because of greed.
