== 💰MONEY

=== Do not spend more than you make
If you need to spend more, make sure you really need to spend that much. 

Try spending only on the things you absolutely need.

If you want to pamper yourself make sure you can afford it without putting yourself in an unconfortable financial situation.

If you're only spending on essentials and you're spending more than you make, make more money.

You can make more money by acquiring more valuable skills, by trading goods/stocks/currencies/other people's services.

=== Track your income and spending
When you're getting started with money, try having a simple spreadsheet to track every dollar that comes in and out of your networth.

This will help you understand the value of your money and time and it will help you realize what you really need and what expenses can be removed from your monthly budget.

=== Avoid debt, however it can be a great tool under the right conditions
Avoid debt unless it's absolutely necessary or you have 10x the collateral to pay it back.

If you will borrow money you must make sure you're paying the right amount of interest for the risk you represent, which should be low if you have 10x the collateral to pay it back.

Debt is enslaving if you struggle to pay it back, and not paying on time means interest will accrue on top of interests making it very hard or impossible to pay. 

Debt however can be a great tool when interest rates are very low, you can see it as "cheap money" if you know with certainty you will grow the capital you've borrowed to make more than the interest you'll be paying on it.
In the US you can tax deduct the interest payments and lower your tax burden.
Debt is useful when the economy shows inflationary signs and you know the value of money is lost at a faster rate than the interest you're paying.

=== Do not invest unless you're willing to lose 100% of that capital

Do not invest vital savings. Do not invest money you or your family will need.

Do not get in debt you can't repay to invest.

You must be able to burn the money you're about to invest and be fine with that. This will remove emotions like fear and greed from your investment strategy and you will be able to follow through with it despite possible temporary crashes or bear cycles, as well as being able to get out of your investment position once your initial target has been met and not lose it because of greed.

=== Do not lend money to friends, do not borrow money from friends

If you lend money to friends, even if you make them sign a contract, in my experience most friends never pay back. You better get ready to lose that money or lose the friendship.

The same also happens with family, learn to say no, ask them if they tried getting a credit line at the bank.

=== Do not use your credit card as a loan

Credit card interests are the highest and you will probably be in debt for years

=== Use your credit card as a debit card

Always pay in FULL the monthly credit card balance. Remember the first tip, don't spend more than what you make, much less with a credit card carrying a high interest rate.

Never pay the minimum payable, if you leave a balance it will quickly compound interests and grow. 

If you need money ask for a loan for a much lower interest rate.

Use your credit card just for its convenience and pay it in full so you start getting a better credit score. A great credit score will open every door. 

A credit card is not free money, it's actually very expensive money.

=== Do not use credit cards with yearly fees

Credit cards are very competitive, usually credit cards with fees present very attractive options, but you must do the math on how much you have to spend in order to get the benefits and most often you realize that it's cheaper to get these by yourself.

There are credit cards with cash back rewards or e-commerce credits, it's great to use these for bigger payments like taxes or insurance claims, just make sure you pay back the debt right away and leave a zero balance.

=== Stand strong before you can help others, not when you are still crawling

If you need to help family or friends, only do so if you can lose 100% of that money without putting a risk to your livelyhood.

If this person keeps asking for your money make sure this person is worth helping and that they're not taking advantage of you.
