= 🤝 PEOPLE

xref:time.asciidoc[⌛ TIME] - xref:body.asciidoc[💪 BODY] - xref:mind.asciidoc[🧠 MIND] - xref:money.asciidoc[💰 MONEY] - xref:work.asciidoc[💼 WORK/LEADERSHIP]

'''


== Don't talk shit behind anybody's back
If you care about them, it's better that you find the way to say things to their face, but try to understand first why they are acting out in a way in which you don't agree.
Lesson from my mother.

== Celebrate other people's victories as your own
Nothing good comes from envy, envy is pathetic. In the end the ego is an illusion, we are all made of the same atoms and energy and we will all die. Stay away from envious people as they never want anything good for you.

== Be loyal and be there for your friends
The best friends are ALWAYS there when you need them and they will never betray you. Be that kind of person for your friends and family.
Lesson from Alden Torres.

== Treat everyone you meet with respect and dignity

Respect: a feeling of deep admiration for someone or something elicited by their abilities, qualities, or achievements.

Dignity: the state or quality of being worthy of honor or respect.

Treat everyone with the utmost respect and dignity, even in failure.

Bill Campbell's lesson.

== Be generous
Share and be generous of your time and resources with friends and family.
Lesson from my best friends.

== Always be yourself, have your own personality
Think for yourself, act for yourself, don't do something you believe isn't right just because others are doing it.
Lesson from my mother.

== Don’t criticize, condemn or complain
This one is really hard for someone like me, as I care a lot about truth and I will say things to people's faces. Try to always find a common ground, or something that you genuinely like about the other person to soften them before you try to make any critic. People's egos are fragile, but they're also easily fed.
[quote]
Criticism is futile because it puts a person on the defensive and usually makes him strive to justify himself. Criticism is dangerous, because it wounds a person’s precious pride, hurts his sense of importance, and arouses resentment. …. Any fool can criticize, condemn and complain—and most fools do. But it takes character and self-control to be understanding and forgiving.

Dale Carnegie's lesson.

== Give honest and sincere appreciation
People can easily smell when you are faking compliments, if you see something you like on the person, praise them generously about it and ask them about it if you have any curiosity. This will feed their ego, and you will be surprised as to what can happen after such praises, specially when you're dealing with somebody giving you some sort of service, in most cases you can get away with more than you thought you'd get.
Dale Carnegie's lesson.

== Smile
Smiles are contagious.
Dale Carnegie's lesson.

== Be courteous
Always say "Please" and "Thank you" when you need something from others. Hold doors for strangers, let other people exit elevators before you, give others your seat in public transport.

== Try to remember people's names
Their names are the foundation of their egos. If you remember someone's names after days, weeks or months, next time you see them you'll blow them away, and they'll feel more important as they have a place in your mind.

== If you're wrong, admit it quickly
Being able to admit you're wrong and changing course is a sign of intelligence. Do not become a prisoner of dogmas nor your ego, this makes you free to grow faster.
Dale Carnegie's lesson.

== Begin in a friendly way
Try to first find a common ground, tell them what they already agree on, get them to start saying yes.
Dale Carnegie's lesson.

== Talk about what they want/like
If you can figure out what is it that matters to others, talk about it, if you don't know anything about try to genuinely ask about it for your own curiosity, this can lead to them talking a lot while you just listen.

This also applies to doing, me being a person who lacks empathy this is very hard, and I always end up having them do what I like to do, which makes it hard to make new friends, but in my case, I tend to prioritize my own time and growth more than the enjoyment of others, and I'm fine with that.

== Surround yourself with positive and genuine people
Stay away from negative people, they are usually those who always complain and don't ever suggest solutions nor take action.
Stay away from people who talk behind other's backs, as they will inevitably envy and talk shit about you.
Better to be alone than in bad company. Lesson from my mother.

== Stay away from liars and thieves
If you catch someone lying or stealing you can't really ever trust them, push them or cut them away from your life as soon as possible.

== Do not lie

== Do not steal

== Don't borrow things
And if you must borrow things, make sure to return them right away.

== Don't lend things
Unless you're willing to lose them or to be nagging people to return them. Most people will borrow things and never return them.

If someone comes asking for something you're not really needing or using anymore, just give it away, as they'll do you the favor to declutter your life.

== Surround yourself with smarter people
It's better to be with people you can learn from, also hardworking, sincere, loyal people.

== Be humble
There is always someone better than you in whatever it is that you do. Be modest.

== Expect to be judged by your appearance
It must be an evolutionary thing, but humans are influenced by plumage.

Don't underestimate what a good appearance can do for you.

Being healthy and fit is the ultimate way to be attractive, desirable, not invisible.

== Don't judge people by their looks
There are many truly smart and powerful people who are very humble and who hate the attention.

Do not judge people by their appearance, clothes, race, if anything judge them by their actions.

This also goes the other way around, other people use plumage to look more interesting, rich, smarter, do not be deceived, pay close attention to their actions.

== Most people's IQ's are under 130 points
Looking at the normal distribution of Intellectual Coefficients, it's clear that most people out in the world are borderline moronic.

Most people are downright stupid and emotional. A lot of what seems simple and a no brainer to you is not so evident for them. Use this to your advantage.

This explains a lot of why the world is the way it is, and why people act so stupidly, and why perhaps it's hard for you to sympathize with others.

Most people make bad decisions because they may also have a low EQ (Emotional Quotient) and they let their emotional side rule them. They act on gut, and not logically seeing what's good, what's bad, and what are the risks.

This might be in big part due to biological factors and/or poor upbringing. Most people don't know much nor try to learn about parenting, and more morons breed even more morons.

At the same time, higher IQ individuals are more selective and more cautious when it comes to reproduction.

== Embrace your differences, exploit them
Don't try to look like something you are not, instead embrace your differences, they are what makes you beautiful and attractive to others.

'''

xref:time.asciidoc[⌛ TIME] - xref:body.asciidoc[💪 BODY] - xref:mind.asciidoc[🧠 MIND] - xref:money.asciidoc[💰 MONEY] - xref:work.asciidoc[💼 WORK/LEADERSHIP]
