= 🤝 PEOPLE

== Don't talk shit behind anybody's back
If you care about them it's better that you find the way to say things to their face, but try to understand first why they are acting out in a way in which you don't agree.
Lesson from my mother.

== Be loyal and be there for your friends
The best friends are ALWAYS there when you need them and they will never betray you. Be that kind of person for your friends and family.
Lesson from Alden Torres.

== Be generous
Share and be generous of your time and resources with friends and family.
Lesson from my best friends.

== Always be yourself, have your own personality
Think for yourself, act for yourself, don't do something you believe isn't right just because others are doing it.
Lesson from my mother.

== Don’t criticize, condemn or complain
This one is really hard for someone like me as I care a lot about truth and I will say things to people's faces. Try to always find a common ground, or something that you genuinely like about the other person to soften them before you try to make any critic. People's egos are fragile, but they're also easily fed.
[quote]
Criticism is futile because it puts a person on the defensive and usually makes him strive to justify himself. Criticism is dangerous, because it wounds a person’s precious pride, hurts his sense of importance, and arouses resentment. …. Any fool can criticize, condemn and complain—and most fools do. But it takes character and self-control to be understanding and forgiving.

Dale Carnegie's lesson.

== Give honest and sincere appreciation
People can easily smell when you are faking compliments, if you see something you like on the person praise them generously about it and ask them about it if you have any curiosity. This will feed their ego and you will be surprised as to what can happen after such praises, specially when you're dealing with somebody giving you some sort of service, in most cases you can get away with more than you thought you'd get.
Dale Carnegie's lesson.

== Smile
Smiles are contagious.
Dale Carnegie's lesson.

== Try to remember people's names
Their names are the foundation of their egos. If you remember someone's names after days, weeks or months, next time you see them you'll blow them away, and they'll feel more important as they have a place in your mind.

== If you're wrong admit it quickly
Being able to admit you're wrong and changing course is a sign of intelligence. Do not become a prisoner of dogmas nor your ego, this makes you free to grow faster.
Dale Carnegie's lesson.

== Begin in a friendly way
Try to first find a common ground, tell them what they already agree on, get them to start saying yes.
Dale Carnegie's lesson.

== Ask questions instead of giving direct orders
Dale Carnegie's lesson on leadership.

== Praise in public, correct in private
Heard this one from Pablo Escobar. Great tip for leadership.

