= Life Tips

This book is an ongoing collection of life lessons from personal experiences and from wiser people than me.

I believe I've had an excellent run so far, I started writing these tips since 2017 on a moleskine notebook when I was 37 years old and had managed to over achieve my dreams. I'm now 42 and every tip I wrote has been reaffirmed and used ever since, in the last 5 years more lessons have come and now that my kids are old enough to start making use of these lessons, it's time to turn this into a short manuscript.

During the last 5 years I've focused on learning more about people, raising my kids I've learned about my own challenges and I have a high degree of certainty that I'm somewhere in the autistic spectrum, a condition that has perhaps been a gift when it comes to productivity and money making, but not so much in dealing with people when it's truly necessary to do so, e.g. personal relationships, social popularity, leadership.

I'm not a person guided by gut, those around me guided by gut feelings and magical thinking seem to be always in an endless clusterfuck while things just line up for me. Life doesn't need to be that hard if you follow sound principles and act based on facts and logic.

This is for you Nicole, Sarah and Desmond.

== Book Structure

Tips have been categorized for what I consider to be the most important aspects of life.

=== xref:time.asciidoc[TIME]
=== BODY
=== MIND
=== WORK/LEADERSHIP
=== PEOPLE
