= ⌛TIME

=== Time is your most expensive resource
Unless you are immortal you will never have enough time. For mortals its supply is uncertain. Do not waste it. Even the universe has its days numbered.

=== Tomorrow is not guaranteed
Today can be your last day, make the most of it

=== Carpe Diem, Carpe Noctem
Squeeze every hour of the day and the night, proper sleep is also an optimization of your next day, see xref:body.asciidoc[BODY]

=== Figure out how you are currently spending your time
Log what you've done throughout the day, use apps to measure your online activity and app usage activity

=== Learn to say no
If you have something more important to do than what they ask of you, say no. You don't know how much time you have left.

=== Wear a wristwatch ⌚
It can be your smartphone, or whatever device you use in the future (smart glasses?), it should have a stopwatch app.
Preferably a Fitbit/Fitness tracker that also tracks steps, heartrate, caloric burn and other vitals, this relates to xref:body.asciidoc[BODY]

=== Use or learn to use a calendar
There's no way you'll be able to achieve important and complex tasks in time if you don't organize your day, week, month, trimester, year.
Planning is guessing but it's good to have an idea of what's coming and what time you have available to tackle things.
If you are in school and most of your time is taken by activities that only require your time as a resource I've found that printing the current month's calendar on paper and then writing/ammending it by hand on it works wonders to manage lots of tasks.
If you have a partner/family/employees/team, a shared online calendar like Google Calendar works well.

=== If you use your time on others, make sure it's worth it
Spend your time with people that have potential to grow or help you grow

=== Don't waste other people's times
This is a version of then silver rule, do not do to others what you don't want don't to you

=== Always be on time
Always calculate for unforseen events and leave early if you can. This will reflect well on your xref:work.asciidoc[WORK] ethic.

=== Learn how to estimate how much time your spend doing different tasks
This will be useful for xref:moneyascii.doc[MONEY] management estimations, expenses estimation, planning. Once again, wear a wristwatch

=== Assign time limits to tasks
Deadlines suck, but they sure as help put pressure to get things done.

=== Prioritize the use of your time
Try working on the hardest tasks first, then the rest will seem easy. This is hard when the most important task has an indeterminate duration (you have no clue if you will be able to solve it in 5 minutes, 5 hours or days). When this happens it's usually best to first dedicate time to understand the problem, such analysis tasks benefit from the previous advice, assigning time limit. You can say, I need to do this very important task that could take me forever, I'll assign a limited amount of fully focused time to understand it, break it into smaller easier sub-tasks, plan it, overcome it.

=== Leverage checklists
Master the use of checklists, prioritized checklists, daily checklists. Group similar tasks together in these checklists.
In my experience, paper checklists work better than any application.

Make sure they are realistic and notice which items stay unchecked for days, weeks months or years, perhaps these are projects on themselves and need to be prioritized and broken into sub-checklists


=== Do what you love and do it often
This is what life is about, this is what you work for, why you want to optimize your time usage, to be able to do what you love.
Caveat: make sure that doing what you love doesn't hurt you or others

=== Keep your things in order
Every day we need to find and use things, many are the same, our key, our wallet, our smartphones, shoes, glasses, etc.
Keeping your room/office/home organized with well defined places for specific things will make those searches not waste you time.
If you find yourself losing where you keep your keys, your remote control, and this happens hundreds of times per year, minutes turn to hours and hours can turn to days over the years.

=== 📝 Ticket based systems work well in small teams
This is both a TIME and xref:work.asciidoc[WORK] tip. Good time management helps in every other aspect of life.

I've only been able to work in teams of about 5 people, and in open source projects with about 100 contributors where tasks are managed by creating "tickets".

Tickets describe what needs to be done and keep track of the issue on the ticket, this works very well for distributed teams. 

They can also be added to a board that groups tickets by columns representing the state of the ticket's lifetime.
