= TIME

===Time is your most expensive resource
Unless you are immortal you will never have enough time. For mortals its supply is uncertain. Do not waste it. Even the universe has its days numbered.

===Figure out how you are currently spending your time

===Learn to say no

===Wear a wristwatch

===Use or learn to use a calendar

===If you use your time on others, make sure it's worth it
Spend your time with people that have potential to grow or help you grow

===Don't waste other people's times
This is a version of then silver rule, do not do to others what you don't want don't to you

===Be on time
Always calculate for unforseen events and leave early if you can

===Learn how to estimate how much time your spend doing different tasks
This will be useful for xref:moneyascii.doc[MONEY] management estimations, expenses estimation, planning.

===Assign time limits to tasks

===Prioritize the use of your time

===Group similar tasks together

===Do what you love and do it often
But make sure that doing what you love doesn't hurt others