= 💼 WORK/LEADERSHIP/ENTREPRENEURSHIP

xref:time.asciidoc[⌛ TIME] - xref:body.asciidoc[💪 BODY] - xref:mind.asciidoc[🧠 MIND] - xref:money.asciidoc[💰 MONEY] - xref:work.asciidoc[💼 WORK/LEADERSHIP] - xref:people.asciidoc[🤝 PEOPLE]

'''

Leadership is about people, make sure to learn all the tips in the xref:people.asciidoc[🤝 PEOPLE] section

== Ask questions instead of giving direct orders
Asking questions is a good way of making them think it was their idea, also, it's a great way to understand why they might be doing things in a way that seems wrong to you. Dale Carnegie's lesson on leadership.

== Praise in public, correct in private
Heard this one from Pablo Escobar. Great tip for leadership.

== Don't have mediocre people in your team
Look for smart, perfectionists, overachievers, people that will tell you what to do to make the company/product/services better. People who were great academically tend to have this qualities in my experience. This doesn't mean people with formal education can't be this way, but outstanding academic performance is a good way to spot them.

== Lead by example
Works better than telling people what to do or even giving advice. People will end up doing the things that are good for them when they are inspired or when they finally figure things out. Actions speak louder than words. Be an inspiration.

== Listen to your team
If you have surrounded yourself with a great team that is.

== Listen to your users/customers
They're an endless source of inspiration. Listen hard and use negative feedback as a challenge.

== Only make changes if they make things better
Remember what your core mission and values are, don't follow trends if they don't align, it's more to maintain and it can ruin your product.

== Release early, release often
Get feedback from your customers as soon as possible

== Learn to prioritize
If there's a wound, first stop the bleeding, then you will be able to think more clearly in times of crisis.

== Do not overplan
Planning is guessing, be ready to adapt and pivot completely if necessary.

== Less is more
Focus only on what's more important and try to deliver the best of it possible as this is usually what your users/customers truly care about.

== Make sure to establish "line of sight" before you begin
Before embarking on any new project, make sure to think through of all the obstacles and aim to solve the hardest ones first if it's not possible to establish line of sight first but it might be worth giving it a try. Fail fast.

Sometimes this means making sure you're not liable or breaking any laws. Know the laws before you embark on new adventures.

Some innovative companies have gone ahead and done it anyway and when they succeed they make laws change. Sometimes lobbying in smaller states can be a powerful (and cheap) tool to push innovation through.

== Do the hardest thing first, fail fast

== Inconvenience is opportunity
Where others see problems you can find business models by providing solutions.

== If you don't like something try to change it
Don't be a complainer, seize the opportunity. Be proactive

== Always do your best
Always try harder

